# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instance_idle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="instance_idle.proto",
    package="aws_connect",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x13instance_idle.proto\x12\x0b\x61ws_connect\x1a\x1fgoogle/protobuf/timestamp.proto"\x90\x01\n\x0cInstanceIdle\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12<\n\x18last_connected_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,
    ],
)


_INSTANCEIDLE = _descriptor.Descriptor(
    name="InstanceIdle",
    full_name="aws_connect.InstanceIdle",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="timestamp",
            full_name="aws_connect.InstanceIdle.timestamp",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="instance_id",
            full_name="aws_connect.InstanceIdle.instance_id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="last_connected_timestamp",
            full_name="aws_connect.InstanceIdle.last_connected_timestamp",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=70,
    serialized_end=214,
)

_INSTANCEIDLE.fields_by_name[
    "timestamp"
].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_INSTANCEIDLE.fields_by_name[
    "last_connected_timestamp"
].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name["InstanceIdle"] = _INSTANCEIDLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstanceIdle = _reflection.GeneratedProtocolMessageType(
    "InstanceIdle",
    (_message.Message,),
    {
        "DESCRIPTOR": _INSTANCEIDLE,
        "__module__": "instance_idle_pb2",
        # @@protoc_insertion_point(class_scope:aws_connect.InstanceIdle)
    },
)
_sym_db.RegisterMessage(InstanceIdle)


# @@protoc_insertion_point(module_scope)
